juju/txn

prune.go, prune_test.go, txn.go
If left alone, the collection used by mgo/txn to coordinate and track client-side transactions will grow without bound.
This change adds a PruneTransactions method to the Runner interface. This can be called at any time to remove mgo/txn's documents for applied and aborted transactions. It is intended to be called periodically.
(Review request: http://reviews.vapour.ws/r/1705/)
=> Added functionality for pruning mgo/txn's transactions collection

prune.go, prune_test.go, txn.go
Instead of just recording details of the last pruning run in the txns.prune collection, details for all pruning runs are now kept. More stats are kept now to allow analysis of pruning performance. For quick access, a pointer document is used to track the most recent result (required for regular pruning checks).
(Review request: http://reviews.vapour.ws/r/1763/)
=> Record historical pruning stats

prune.go, prune_test.go
The prune.* files were ascribed the AGPLv3 licence by mistake. This project is LGPLv3 for original work.
This fixes an issue raised by Ubuntu regarding 1.22.5. They will accept the package if we show that this issue is fixed in master.
https://bugs.launchpad.net/juju-core/+bug/1463455
(Review request: http://reviews.vapour.ws/r/1898/)
=> Fix prune.* licence header.

prune_test.go, txn.go, txn_test.go
Also updates the prune test's use of loggo.
(Review request: http://reviews.vapour.ws/r/5662/)
=> Retry errors that finish with 'unexpected message'.

prune.go
Use bulk document removal, rather than
a single RemoveAll with a query of "_id $in [...]".
The latter has performance problems in some
configurations of MongoDB. See https://bugs.launchpad.net/juju/+bug/1635311.
Excerpt from the bug:
> Today I did the test again on the Azure instance where the issue was reproduced, instead of my local system where I did it first. On there, Mongo does not like the method used at all. In the logs from Comment 6, there's a log message stating that ~9000 transactions need pruning. Using the method from Juju, removing 10000 docs took about 2 minutes in one test. I wrote some more optimised code which does the same thing ~instantly.
(Review request: http://reviews.vapour.ws/r/5955/)
=> Use mgo.Collection.Bulk to prune docs

prune.go
Previously, transaction pruning would consume unmanagable amounts of
memory when large numbers of transactions were present.
Instead of holding the transaction ids working set in memory, it is
now kept in a temporary database collection (generated by an
aggregation pipeline query) which uses much less memory.
Also of note:
- queries now use the maximum batch size to maximise throughput
- bulk record removal has been abstracted into a bulkRemover
- type (much cleaner)
- progress for long running operations is now emitted using a timer
resulting in less noise and more useful feedback
As well as consuming less memory, the new approach is also much
faster. Using a real-world database dump containing 19 million
transactions where 18.5 million were to be pruned, the total prune
time dropped …
=> Use disk-based pruning strategy

cleaner.go, prune.go, prune_test.go
This creates a CollectionCleaner type that can be used to remove transaction entries that have already been completed. It is actively used on the txns.stash collection to remove documents that are no longer needed.
This is able to handle 300k documents in txns.stash in less than a minute, so it feels good to include as a regular operation as part of our normal txn pruning. (memory consumption with a cache of 1M removed items hits at most 1GB, but the default cache size is restricted to less than that.)
This should do bulk updates to documents and bulk removals to the txns.stash. I haven't wired it up to remove stale references from all collections yet, but that shouldn't be too hard to add.
Addresses: https://bugs.launchpad.net/juju/+bug/1678587
(Review request: …
=> Cleanup txn.Stash as part of regular pruning

cleaner.go, prune.go, prune_test.go, txn.go
This builds on my previous patch to cleanup the txns stash.
The actual changes here are fairly small once that one lands. This just adds CleanupAllCollections and updates the test suite to handle the fact that last-updated-transactions are no longer left in the documents.
It also includes "statuseshistory" as an explicitly omitted table, because it is not worth processing (its big, and never uses txns.)
(Review request: http://reviews.vapour.ws/r/6494/)
=> Cleanup all collections

txn.go
This may fix: https://bugs.launchpad.net/juju/+bug/1680786
It doesn't let us know who is creating no-op transactions,
but it does feel like it isn't worth committing them to
the database.
We did already have ErrNoOperations to signal something similar, but it seems to me that we should either treat no-operations as either the same thing, *or* we should actually treat it as an error. If you'd prefer an error, I can do that, but we then need to track down the places that are creating these, so we don't have production failures.
(Review request: http://reviews.vapour.ws/r/6508/)
=> Don't create transactions that have no operations.

cleaner.go, export_test.go, oracle.go, oracle_test.go, prune.go, prune_test.go, txnsuite_test.go
This brings in an Oracle interface, which allows us to track completed transactions either in-memory or using the $out aggregation.
I decided to use a check on how-many-transactions there are as to whether we would use the in-memory one.  My suspicion is that pruning got faster because we were deleting in database order, rather than just because of disk vs memory. So the MemOracle sorts the transaction ids before returning them.
I haven't had a chance to test this on the big database, or on a live test server, so it does need a bit of direct testing to flush out anything else.
I also ran into the fact that doing c.Skip() in SetUpTest causes go-check to also skip calling TearDownTest which sucks, cause it means I can't put the db version check into a common place. (SetUpSuite doesn't have …
=> Abstract out "Completed Transaction" functionality

txn.go, txn_test.go
Oddly enough we didn't have a test that we handled errors correctly.
The issue is that often when raising an error, we also set the ops to empty,
so we have to check the error before we do the rest.
Add a test that we handle these cases correctly.
(Review request: http://reviews.vapour.ws/r/6516/)
=> Properly test no-op does the right thing, as does real errors.

cleaner.go, prune.go
This gives a bit nicer set of information at INFO level. That doesn't
overwhelm you with the details, but can give you a general idea of what
has been done.
As part of doing manual testing with accelerated pruning, I felt it would be nice to really see what was going on. (running cs:~jameinel/peer-xplod with 24 units spread across 4 containers is a decent load test. I'd like to understand why jujud-machine-0 is at 236%CPU while mongo is only 33% CPU, but that's for another day.)
The log messages look like:
```
machine-0: 17:37:19 INFO juju.txn txns after last prune: 5, txns now: 122, pruning required: true transactions have grown significantly
machine-0: 17:37:20 INFO juju.txn txn pruning complete after 412.843118ms. txns now: 4, inspected 56 collections, 51 docs (46 cleaned)
removed 0 …
```
=> Add logging information about the pruning result.

oracle.go
2.4 fails if the total size of the aggregation is too big,
while in 3.2 it only fails if the size of an individual doc
gets too big.
Running mgopurge against big 2.4 databases was failing
(2.4M txns * 20 bytes per ID is >16MB).
We already switched to just loading them one-by-one, it probably isn't much slower to use a Find() as we aren't doing anything fancy like $group.
(Review request: http://reviews.vapour.ws/r/6547/)
=> Turns out it isn't safe to use aggregation in 2.4 at all.

cleaner.go, prune.go
Mongo 2.4 doesn't support bulk operations anyway, but this still
allows us to do a little bit more batching instead of removing
exactly one-by-one.
Just introduces another Remover type and switches between them based on $out support.
That may not be the exactly right signal, but it is a close approximation that didn't make me
need to think about it significantly.
=> support using RemoveAll($in) instead of Bulk.

cleaner.go, cmd/txncleaner/main.go, export_test.go, oracle.go, oracle_test.go, prune.go
Pass CleanAndPrune arguments as a struct
In preparation for adding more.
---
Avoid unnecessarily passing db around
The pruning related functions often took both a `mgo.Collection` and a
`mgo.Database`. This was unnecessary given that the database can be
retrieved from the collection. It is also safer to pass them together
given that the collection's database should never be different to the
given database.
=> Various cleanups

oracle.go, oracle_test.go, prune.go
This tracks 'references' separately from 'removals'. So we track what transactions are referenced, and we want to be safe that we aren't pruning them, but separately track whether the reference was actually in the set that we would have removed.
=> track what is actually removed by Oracle.RemoveTxns()

export_test.go, oracle.go, oracle_test.go, prune.go, prune_test.go, txn.go, txnsuite_test.go
This allows us to set a time threshold for what transactions
we will treat as completed/aborted. Callers can then set a value
and we will not prune transactions that are newer than that time.
=> Expose a NewestTime for PruneOptions.

prune.go
If err is ErrNotFound then result will be nil, triggering a panic.
Fixes https://bugs.launchpad.net/juju/+bug/1697795
=> Handle Bulk.Run() result being nil

txn.go, txn_test.go
Given the Clock is only used when observing transactions, it seemed
silly to mandate everyone pass one in.
=> Change Clock back to being optional.

export_test.go, oracle.go, oracle_test.go, prune.go, txn.go
Just a minor tweak.
Also add some extra logging if we don't clear out all the txns that we expect.
=> No need for uint64 and it makes default printing *ugly*

cleaner.go, prune.go, prune_test.go, txn.go
Some cleanups to allow using the new txn pruner with the Juju 2.4 codebase.
* Remove some unused code, this is mostly just to simplify the code, cleaning it up a bit.
* Use a simplified Clock interface. This is because `github.com/juju/clock` is not actually compatible with `github.com/juju/utils/clock` because one of the interface return values is a typed struct. We don't need that method, so this allows us to be compatible with both forms.
* Juju uses the MaybePruneTransactions as its method for interacting with juju/txn, so we need to pass some more variables through.
I'll have a follow up on Juju that makes use of the new parameters to control pruning.
Related juju update: https://github.com/juju/juju/pull/9594
=> 2.4 prune options

txn.go, txn_test.go
The following changes pass the transaction attempt through to the
RunTransaction, which can then pass it on to the observer. This
should hopefully allow us to then workout how many attempts and the
duration of the transaction operation.
@jameinel in regards to "RunTransactionObserver doesn't currently take the time for the transaction into account", isn't the `Duration` on `ObservedTransaction` doing that?
=> Pass the transaction attempt

txn.go, txn_test.go
The following changes are formalising a discussion[1] from a previous
PR #48, where it might make more sense to pass the ObservedTransaction
through.
There are a couple of things to note:
1. I renamed ObservedTransaction to Transaction, as it no longer
observes the transaction, it's actually used when calling the
runner. With this in mind I renamed it as it made more sense.
2. I left the ObservedTransaction as value object rather than a
pointer when it is passed to runTransactionObserver so that it
implies immutability (even though you can modify the Ops etc).
- 1 https://github.com/juju/txn/pull/48#discussion_r250203789
=> Thread through the transaction

testing/testing.go
This PR provides some more context to unassuming new developers who are learning about BeforeHooks/AfterHooks.
Using check's comment feature, this message is displayed:
```plain
// At least one hook has not run. Some common causes:
// - forgetting to prefix the call to Check() with defer
// - checks in the build function failing, so the slice of txn.Ops never gets run
// - miscalculating the number of hooks and/or attempts
c.Assert(remaining, gc.HasLen, 0)
... obtained []txn.TestHook = []txn.TestHook{txn.TestHook{Before:(func())(0x2f78a10), After:(func())(0x2f78bb0)}, txn.TestHook{Before:(func())(0x2f78a10), After:(func())(0x2f78bb0)}, txn.TestHook{Before:(func())(0x2f78a10), After:(func())(0x2f78bb0)}}
... n int = 0
```
Hopefully this is more useful to newcomers than the bald Assert …
=> Add help text to explain why hooks do not run

incrementalprune.go
If txns.RemoveAll returns an error, it also returns a nil result
pointer. The old code would propagate the error, but not until after it
accessed attributes of the nil result.
Addresses https://bugs.launchpad.net/bugs/1903202
It doesn't fix any underlying error, but it avoids having an error turn into a panic().
I didn't see a clean way to inject errors into the system, though I'm still looking. I mostly wanted to propose a possible fix so we can find progress.
=> Properly handle when RemoveAll returns an error.

cmd/txncleaner/main.go, go.mod, go.sum, oracle_test.go, prune_test.go, testing/testing.go, txn.go, txn_test.go
Server side transactions run much faster (orders of magnitude) than client side ones, and so the possibility for contention is much greater when running many concurrent transactions. With only 3 retries, it's possible and likely that concurrent txns will never succeed.
This PR adds extra tuning parameters to the txn retry logic and also makes those parameters configurable so callers like Juju can tune them as needed.
The default retry count for SSTXN is now 50 and there's a small delay (plus fuzz) introduced between each retry.
Tested by running go tests in the juju state package. The retry count was somewhat adjusted empirically until the tests passed.
=> Add extra txn backoff tuning parameters for sstxn

txn.go, txn_test.go
Add support for no change log when committing transactions by passing "-" as the change log collection name, since empty string causes it to default, "-" was used instead.
=> Add support for no change log, used when upgrading to SSTXN.

.gitignore, txn.go, txn_test.go
Adds two extra hooks for sstxn manipulation for testing.
- Started hook is called after StartTransaction on the mgo.Session.
- Asserted hook is called after transaction assertions have been made.
=> Add started and asserted hooks for sstxn testing.

txn.go
Use errors.ConstError for constant errors to simplify juju over the wire error handling.
=> Use juju/errors.ConstError for errors

.gitignore, txn.go
Brings errors inside v2 in line with errors in v3
=> Use const errors for exported errors.
